//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COVID19.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COVID19.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRITICAL.
        /// </summary>
        internal static string CountryCritical {
            get {
                return ResourceManager.GetString("CountryCritical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Country.
        /// </summary>
        internal static string CountryPicker {
            get {
                return ResourceManager.GetString("CountryPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search a Country....
        /// </summary>
        internal static string CountrySearch {
            get {
                return ResourceManager.GetString("CountrySearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODAY CASES.
        /// </summary>
        internal static string CountryTodayC {
            get {
                return ResourceManager.GetString("CountryTodayC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODAY DEATHS.
        /// </summary>
        internal static string CountryTodayD {
            get {
                return ResourceManager.GetString("CountryTodayD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CASES.
        /// </summary>
        internal static string MainCases {
            get {
                return ResourceManager.GetString("MainCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Here.
        /// </summary>
        internal static string MainContinue {
            get {
                return ResourceManager.GetString("MainContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEATHS.
        /// </summary>
        internal static string MainDeaths {
            get {
                return ResourceManager.GetString("MainDeaths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECOVERED.
        /// </summary>
        internal static string MainRecovered {
            get {
                return ResourceManager.GetString("MainRecovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Status.
        /// </summary>
        internal static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to know the current status in your country.
        /// </summary>
        internal static string MainTitleContinue {
            get {
                return ResourceManager.GetString("MainTitleContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string MsgClose {
            get {
                return ResourceManager.GetString("MsgClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country not Found!.
        /// </summary>
        internal static string MsgCountryError {
            get {
                return ResourceManager.GetString("MsgCountryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current virus status in.
        /// </summary>
        internal static string MsgCountryStatus {
            get {
                return ResourceManager.GetString("MsgCountryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again!.
        /// </summary>
        internal static string MsgError {
            get {
                return ResourceManager.GetString("MsgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong....
        /// </summary>
        internal static string MsgErrorTitle {
            get {
                return ResourceManager.GetString("MsgErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields can not be empty!.
        /// </summary>
        internal static string MsgFieldEmpty {
            get {
                return ResourceManager.GetString("MsgFieldEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your internet Connection and Try Again!.
        /// </summary>
        internal static string MsgInternet {
            get {
                return ResourceManager.GetString("MsgInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string MsgLoad {
            get {
                return ResourceManager.GetString("MsgLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got It.
        /// </summary>
        internal static string MsgOk {
            get {
                return ResourceManager.GetString("MsgOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This information is updated!.
        /// </summary>
        internal static string MsgUpdate {
            get {
                return ResourceManager.GetString("MsgUpdate", resourceCulture);
            }
        }
    }
}
